### ISSUE TITLE
Add about section in website

### ISSUE THREAD

**Issue by Aayush-hub** [Srimathij/Indra_Bot#34] opened 2021-03-25 11:53 UTC
## What UI bug/error you faced? Could you describe?

We can add a informative about section to the website which can tell users what the project is for and can also celebrate the creators and contributors of this project there.

**Comment by arpit456jain** [comment] 2021-03-25 14:00
Sir Can I work on this issue

**Comment by arpit456jain** [comment] 2021-03-25 14:01
I am a Gssoc'21 participant.

**Comment by techpkd123** [comment] 2021-03-25 14:06
Sir can i work upon this issue as a GSSoC'21 participant?

**Comment by Aayush-hub** [comment] 2021-03-25 14:10
@techpkd123 @arpit456jain @alphaX86  I am working on it. Kindly give me some time to create a PR.

**Comment by alphaX86** [comment] 2021-03-25 14:14
Right assigning you @Aayush-hub

**Comment by Varun8216889** [comment] 2021-03-25 18:02
As a beginner, I want to contribute but I am not able to find the issue.
Can I start my contribution by working on this issue under GSSoC'21? Kindly assign it to me or suggest me one.

**Comment by alphaX86** [comment] 2021-03-26 01:31
@Varun8216889 to avoid confusion I made a label called "Status:Assigned" which means the Issue is already WIP.

**Comment by alphaX86** [comment] 2021-03-26 01:31
If the issue is made "Status:Ready for grab" then only you can ask

**Closed as completed** 2021-03-26 16:42 UTC
Labels: bug, Status: Assigned :lock:, gssoc21, Level2
